/**
 * Task entity from backend API
 * Matches the Task model from backend (Phase 2)
 */
export interface Task {
  /** Unique task identifier (auto-generated by backend) */
  id: number;

  /** Task title (required, max 200 characters) */
  title: string;

  /** Task description (optional, max 1000 characters) */
  description: string | null;

  /** Completion status */
  completed: boolean;

  /** Owner user ID (set by backend from JWT token) */
  user_id: number;

  /** Creation timestamp (ISO 8601 format) */
  created_at: string;

  /** Last update timestamp (ISO 8601 format) */
  updated_at: string;
}

/**
 * Payload for POST /api/tasks
 * User ID is extracted from JWT token by backend
 */
export interface TaskCreate {
  /** Task title (required, max 200 characters) */
  title: string;

  /** Task description (optional, max 1000 characters) */
  description?: string | null;
}

/**
 * Payload for PUT /api/tasks/{id}
 * All fields are optional - only provided fields are updated
 */
export interface TaskUpdate {
  /** Updated task title (optional, max 200 characters) */
  title?: string;

  /** Updated task description (optional, max 1000 characters) */
  description?: string | null;

  /** Updated completion status (optional) */
  completed?: boolean;
}
